In [11]:
import numpy as np

In [12]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [13]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [14]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [15]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [16]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [17]:
a1 // a2

array([0, 0, 0, 0, 0])

In [18]:
a1 ** 2

array([ 1,  4,  9, 16, 25])

In [20]:
l = [10,20,30,40,50]
arr = np.array(l)

In [21]:
arr + 10

array([20, 30, 40, 50, 60])

In [22]:
arr = np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [23]:
arr + 20

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [24]:
arr * 2

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [45]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [46]:
slice = a[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [47]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [48]:
a
b = a.copy()

In [49]:
b[0] = 99

In [50]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [51]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [52]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

In [53]:
matrix1

array([[1, 2],
       [3, 4]])

In [54]:
matrix2

array([[5, 6],
       [7, 8]])

In [55]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 32]])

In [56]:
matrix1 @ matrix2

array([[19, 22],
       [43, 50]])

In [57]:
matrix1

array([[1, 2],
       [3, 4]])

In [58]:
matrix1.T

array([[1, 3],
       [2, 4]])

In [63]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [64]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [68]:
c= np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [71]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]