In [1]:
import numpy as np

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[9]

np.int64(20)

In [5]:
arr[1:6]

array([12, 13, 14, 15, 16])

In [6]:
arr[0:10:2]

array([11, 13, 15, 17, 19])

In [7]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [16]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [17]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [18]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [25]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])