In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [1,2,3,4,3.5]
a

[1, 2, 3, 4, 3.5]

In [8]:
np.array(a)

array([1. , 2. , 3. , 4. , 3.5])

In [9]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [22]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [24]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr = np.linspace(1,5,100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [28]:
np.random.rand(10)

array([0.59104487, 0.94128507, 0.08364967, 0.27671943, 0.48223293,
       0.93388514, 0.83554474, 0.5911401 , 0.10805269, 0.98303715])

In [29]:
np.random.randn(10)

array([ 0.55228886,  0.29621424, -0.22720834, -0.68880905,  1.05376617,
       -2.1219172 , -0.63266789,  0.04186952, -0.23706127, -0.34168219])

In [46]:
np.random.randint(10,20,10)

array([16, 14, 18, 11, 14, 10, 16, 17, 11, 18], dtype=int32)

In [40]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.shape

(3, 3)

In [61]:
arr.size

30

In [44]:
arr.dtype

dtype('int64')

In [48]:
arr.min()

np.int64(1)

In [49]:
arr.max()

np.int64(9)

In [50]:
arr.sum()

np.int64(45)

In [51]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [52]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [55]:
arr.mean()

np.float64(5.0)

In [56]:
arr.std()

np.float64(2.581988897471611)

In [57]:
arr.argmax()

np.int64(8)

In [58]:
arr.argmin()

np.int64(0)

In [59]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [62]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])