In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
l = [1,2,3,4,5.55]
l

[1, 2, 3, 4, 5.55]

In [4]:
arr = np.array(l)
arr

array([1.  , 2.  , 3.  , 4.  , 5.55])

In [5]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
arr = np.array(l)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [9]:
arr = np.zeros((4,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
arr = np.linspace(1,5,50)
arr

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [16]:
arr = np.random.rand(10)
arr

array([0.2070664 , 0.42491273, 0.77979115, 0.49224972, 0.40104135,
       0.35210745, 0.94100508, 0.05319716, 0.91136634, 0.97211569])

In [18]:
arr = np.random.randn(10)
arr

array([-0.79499267,  0.17452242, -0.45393432,  1.2326659 , -0.17125535,
       -0.45575447, -0.42580143,  0.27433331, -1.39527063,  0.93580162])

In [19]:
arr = np.random.randint(1,10,5)
arr

array([1, 6, 4, 9, 4], dtype=int32)

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape

(3, 3)

In [22]:
arr.size

9

In [23]:
arr.dtype

dtype('int64')

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [28]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.argmax()

np.int64(8)

In [31]:
arr.argmin()

np.int64(0)

In [32]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [33]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [34]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
arr[1]

np.int64(12)

In [36]:
arr[0:5:1]

array([11, 12, 13, 14, 15])

In [37]:
arr[0:10:2]

array([11, 13, 15, 17, 19])

In [38]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [39]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [40]:
arr[:,0]

array([ 1,  7, 13, 19, 25])

In [42]:
arr[4,5]

np.int64(30)

In [43]:
arr[0:4,1:5]

array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23]])

In [45]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [47]:
arr[bool_index]

array([12, 14, 16, 18, 20])

In [48]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [49]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [50]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [51]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [52]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
a1 // a2

array([0, 0, 0, 0, 0])

In [54]:
a1 ** a2 

array([      1,     128,    6561,  262144, 9765625])

In [55]:
l = [10,20,30,40,50]
arr = np.array(l)

In [56]:
arr + 10

array([20, 30, 40, 50, 60])

In [57]:
arr = np.arange(1,51).reshape(5,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [58]:
arr + 20

array([[21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65, 66, 67, 68, 69, 70]])

In [59]:
arr * 2

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [67]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
slice = a[0:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [69]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
a
b = a.copy()

In [71]:
b[0] = 99

In [72]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [75]:
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

In [76]:
matrix1

array([[1, 2],
       [3, 4]])

In [77]:
matrix2

array([[5, 6],
       [7, 8]])

In [78]:
matrix1 * matrix2

array([[ 5, 12],
       [21, 32]])

In [79]:
matrix1 @ matrix2

array([[19, 22],
       [43, 50]])

In [81]:
matrix1

array([[1, 2],
       [3, 4]])

In [82]:
matrix1.T

array([[1, 3],
       [2, 4]])

In [83]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [84]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [85]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [87]:
c = np.arange(0,16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [89]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [96]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [97]:
s.sum()

np.int64(405)

In [102]:
a = np.sum(s,axis = 0)
for i in a:
    if i == 45:
        print("Sudoku is valid for rows.")

    else:
        print("Sudoku is not valid for rows.")
        break

Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.
Sudoku is valid for rows.


In [103]:
b = np.sum(s,axis = 1)
for i in b:
    if i == 45:
        print("Sudoku is valid for columns.")

    else:
        print("Sudoku is not valid for columns.")
        break

Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.
Sudoku is valid for columns.


In [105]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [123]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [124]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [125]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [126]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [127]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [128]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [130]:
#Increase Math marks of all students by 5.
data[:,1] = data[:,1] + 5
data

array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [ 18,  75,  70],
       [ 20, 100,  85]])

In [131]:
#Find how many students are younger than 19.
data[data[:,0] < 19]

array([[18, 95, 78],
       [17, 86, 95],
       [18, 75, 70]])

In [132]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:3],axis = 0)

array([91.6, 83.2])

In [136]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[ 19, 102,  88],
       [ 17,  86,  95],
       [ 20, 100,  85]])